resources:
- configmap.yaml
- deployment.yaml
- job.yaml
- service.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: webhook
  newName: kuda4bigo/webhook
  newTag: latest
- name: webhook-init
  newName: kuda4bigo/webhook-init
  newTag: latest
