# permissions for end users to view data.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: data-viewer-role
rules:
- apiGroups:
  - data.kuda.io
  resources:
  - datas
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - data.kuda.io
  resources:
  - datas/status
  verbs:
  - get
