apiVersion: v1
kind: ServiceAccount
metadata:
  name: webhook
  namespace: system
  labels:
    app: webhook

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: webhook-init
  namespace: system
  labels:
    app: webhook-init
